### PR TITLE
Initial support for NSO applet (by ELY3M)

### PR DESCRIPTION
**Pull request by ShadowOne333**
Based on the fork by @ELY3M mentioned in issue #73.
This should add standard support for editing and dumping the NSO applet.

Needs extra work (according to ELY3M) to be able to change the background color of the icon.

### CODE REVIEW

**Comment by exelix11** [comment]
It doesn't seem to add much aside from some needed definitions and from what i understand it doesn't actually work.
I'm not currently interested in developing new features, i'm closing this unless you're actually willing to finish implementing it.

**Comment by ELY3M** [comment]
Thank you for helping with this.  I will do testing later.  it will be on my fork if it is working for me.

**Comment by ELY3M** [comment]
actually, it is working for me.  I have to do tweaking with layout json and stuff.  I ended up using black background and it look better on my switch.     this is one way to get rid of red background is this layout json at https://pastebin.com/c3HFRRQS

**Comment by ELY3M** [comment]
here is layout json with all black background.  I am using this layout right now.  
https://pastebin.com/4JhN3UGV

**Comment by exelix11** [comment]
Are you sure there is no way of to make it look like the other buttons like by copying over the properties ? Maybe the code behind doesn't theme it at all so it is impossible, idk.
Changing all of them so they match feels hacky and probably breaks the system color "themes".

**Pull request closed without merging**
