### PR TITLE
Create main.yml

### PR DESCRIPTION
**Pull request by tiansongyu**
I thought devkitPro/pacman have the libs that the app need  .  You can watch it(https://github.com/devkitPro/pacman/releases)
I think my action is fine .
It's my pleasure to check out the app

### CODE REVIEW

**Comment by tiansongyu** [comment]
I thought github workflow is a good  way of distinguishing automated builds from release ones .
the newer （container: devkitpro/devkita64:latest ）  have the environment of the switchapp need.
so using the workflow can make sure the code of release one is fine

**Comment by exelix11** [comment]
It is but want to show the commit in the build, keep this PR open, as soon as I have some time will merge it.

You're right the dkp package does seem to contain all libs already, on pc you usually install them manually.

**Comment by tiansongyu** [comment]
ok!!!

**Comment by exelix11** [comment]
Huh, it's been a while.
An update on this: I've finally finished adding automatic building with github actions in the githubCI branch and will be merging into master soon so i'm closing this.
In the meantime automated builds are already available in the [actions page](https://github.com/exelix11/SwitchThemeInjector/actions)

**Pull request closed without merging**
