### PR TITLE
This workflow should be worked ,but it's not 

### PR DESCRIPTION
**Pull request by tiansongyu**
Actually,I want to add a language option for this app. Chinese people like this app so much.They ask me to translate this app.I try to do it .But as you know I cannot pass the link .I thought  it's my environment'fault.because maybe I lost some lib in my computer.
And  I write a workflow in github .As you can see ,it is should be workd ,but it's not .It gave me the fault Exactly as the same as my two computer.
```
/opt/devkitpro/devkitA64/lib/gcc/aarch64-none-elf/10.1.0/../../../../aarch64-none-elf/bin/ld: BaseEntry.o: in function `NxEntry::NxThemeGetBgImage()':
BaseEntry.cpp:(.text._ZN7NxEntry17NxThemeGetBgImageEv[_ZN7NxEntry17NxThemeGetBgImageEv]+0x1d8): undefined reference to `DDSConv::ImageToDDS(std::vector<unsigned char, std::allocator<unsigned char> > const&, bool, int, int)'
/opt/devkitpro/devkitA64/lib/gcc/aarch64-none-elf/10.1.0/../../../../aarch64-none-elf/bin/ld: BaseEntry.cpp:(.text._ZN7NxEntry17NxThemeGetBgImageEv[_ZN7NxEntry17NxThemeGetBgImageEv]+0x2e8): undefined reference to `DDSConv::GetError[abi:cxx11]()'
/opt/devkitpro/devkitA64/lib/gcc/aarch64-none-elf/10.1.0/../../../../aarch64-none-elf/bin/ld: BaseEntry.o: in function `NxEntry::DoInstall(bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
BaseEntry.cpp:(.text._ZN7NxEntry9DoInstallEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN7NxEntry9DoInstallEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x1bb8): undefined reference to `DDSConv::ImageToDDS(std::vector<unsigned char, std::allocator<unsigned char> > const&, bool, int, int)'
```

Could you check out the workflow ,and tell me why the workflow can't build pass .

### CODE REVIEW

**Comment by exelix11** [comment]
Not really familiar to github workflows, could it be that it doesn't have all portlibs installed? The UI depends on Mesa and opengl and probably some other libs as well. You're supposed to install them with dkp-pacman

**Comment by exelix11** [comment]
I'm not sure why you get link errors to `DDSConv::GetError` and `DDSConv::ImageToDDS` as they're part of the code. Checking the logs in your branch the DDSConv.o object file related to [this source file](https://github.com/exelix11/SwitchThemeInjector/blob/master/SwitchThemesNX/source/SwitchThemesCommon/Bntx/DDSconv/DDSConv.cpp) doesn't get compiled at all, no clue why.

**Comment by exelix11** [comment]
This should fix your issue.
The casing for the DDSconv in the makefile folder was wrong, not sure why it doesn't fail for me as i've switched to building on linux as well.

**Comment by tiansongyu** [comment]
Thank you so much ！！:)

**Comment by exelix11** [comment]
Nevermind it just failed. Still doesn't find the same file me check all the paths.

**Comment by exelix11** [comment]
Uhm you closing the PR deleted the branch and it still didn't build.
Anyway as soon as i get some free time will try to add actions to this repo directly, need to find a way of distinguishing automated builds from release ones first.

**Comment by tiansongyu** [comment]
ok .Thank for your work

**Pull request closed without merging**
